### PR TITLE
Release 0.5

### PR DESCRIPTION
**Pull request by bilgili**

### CODE REVIEW

**Comment by favreau** [comment]
+1

**Comment by hernando** [comment]
Check if commits 794cccb and b3519f9 should also go to the release notes.
Are .gitsubprojects and .gitexternals up to date?

**Comment by bilgili** [comment]
- 794cccb can be added has it already in the doc/feature/httpServer.md, it will be kind of redundant, but it is also part of Release. I dont know what to do, open to suggestions.
- b3519f9 Deprecation should go to release notes or so, I have no clear idea

**Comment by hernando** [comment]
Deprecation is something that affects client code, so my opinion it needs to be in the release notes.

**Comment by eile** [comment]
794cccb has been a change within the release, and as such does not need special mention (it's like fixing a regression introduced after the last release)

**Comment by eile** [comment]
b3519f9 Should be mentioned. I forgot to do this in the commit.

**Comment by bilgili** [comment]
ping

**Comment by hernando** [comment]
Don't forget tagging and the documentation upload.

**Pull request merged**
